### ISSUE TITLE
Reboot server -> bar empty

### ISSUE THREAD

**Issue by xzefir** [DosMike/Brotkasten#5]
Hello !
When the server start the boss bar is empty, look at the picture.
I'm nothing in my config file
I use the version 0.4.
Sorry if my english is not perfectly im french :)

![4B8696AC-23F0-4EA8-9B26-7214E015EADE](https://user-images.githubusercontent.com/42659411/62957169-89053300-bdf4-11e9-9742-d91f62615466.jpeg)

**Comment by DosMike** [comment]
what does your config look like?

**Comment by xzefir** [comment]
thank you for your quick answer, here is my config :

# Messages that will be displayed as boss bar
BossBar {
}
# Messages that will be displayed in chat
Chat {
}

**Comment by DosMike** [comment]
ah, so you just want to use the commands?
I'll take a look :)

**Comment by xzefir** [comment]
yes I only use the commands, thank you and good job ! :)

**Comment by DosMike** [comment]
should be done
